databases:
  - name: dpg-clmvjhj8772c73e2k6f0-a
    databaseName: dbmain_2pho
    user: main

services:
  - type: web
    name: config
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: config
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4