# Generated by Django 4.2.7 on 2023-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTarefasFat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('foi_finalizada', models.BooleanField(default=False)),
                ('foi_arquivada', models.BooleanField(default=False)),
            ],
        ),
    ]
