# Generated by Django 4.2.7 on 2023-11-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbtarefasfat',
            options={'ordering': ['id']},
        ),
    ]
