# Generated by Django 4.2.7 on 2023-11-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_tbtarefasfat_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbtarefasfat',
            table='tb_tarefas_fat',
        ),
    ]
